version: '3'
services:
  prometheus:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.route-prefix=/
      - --storage.tsdb.retention.time=200h
      - --web.enable-lifecycle
    links:
      - cadvisor
      - node-exporter

  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always

  #alertmanager:
  #  image: prom/alertmanager
  #  container_name: alertmanager
  #  volumes:
  #    - ./alertmanager:/etc/alertmanager
  #  command:
  #    - --config.file=/etc/alertmanager/config.yml
  #    - --storage.path=/alertmanager
  #  restart: always
  #  ports:
  #    - 9093:9093

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always
    links:
      - prometheus

volumes:
  grafana-data:
