version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.route-prefix=/
      - --storage.tsdb.retention.time=200h
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    links:
      - cadvisor
      - node-exporter

  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    ports:
      - 9100:9100

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    restart: always
    ports:
      - 9113:9113
    entrypoint:
      - /usr/bin/exporter
      - -nginx.scrape-uri
      - http://host_ip/metrics
      - -nginx.retries=10
      - -web.telemetry-path=/metrics

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: always
    privileged:
      true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    build:
      context: .
    container_name: grafana
    restart: always
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: https://grafana.example.com/
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_LOG_FILTERS: rendering:debug
    ports:
      - 3000:3000
    links:
      - prometheus
      - renderer

  renderer:
    image: grafana/grafana-image-renderer
    container_name: renderer
    restart: always
    ports:
      - 8081:8081
    environment:
      ENABLE_METRICS: 'true'

volumes:
  grafana_data:
