global:
  resolve_timeout: 5m
route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-receiver'
receivers:
- name: 'null'
- name: email-receiver
  email_configs:
  - to: freelancer@eduardevops.io
    from: freelancer@eduardevops.io
    smarthost: mail.privateemail.com:587
    auth_username: "freelancer@eduardevops.io"
    auth_identity: "freelancer@eduardevops.io"
    auth_password: "123456"
    send_resolved: true

route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: $GMAIL_ACCOUNT
    from: $GMAIL_ACCOUNT
    smarthost: smtp.gmail.com:587
    auth_username: "$GMAIL_ACCOUNT"
    auth_identity: "$GMAIL_ACCOUNT"
    auth_password: "$GMAIL_AUTH_TOKEN"
EOF
./alertmanager &
