# Prometheus global config
global:
  scrape_interval:     20s
  evaluation_interval: 20s

  external_labels:
    monitor: 'monitor'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx-exported'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'image-rendering'
    static_configs:
      - targets: ['renderer:8081']
