# Prometheus global config

global:
  scrape_interval:     20s
  evaluation_interval: 20s

  external_labels:
    monitor: 'monitor'

rule_files:


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'nginx-exported'
    scrape_interval: 1m
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['nginx-exporter:9113']


# vim /etc/docker/daemon.json

# {
#  "metrics-addr" : "127.0.0.1:9323",
#  "experimental" : true
# }

# curl localhost:9113/metrics
